sudo: required
services:
    - docker 
before_install:
    - openssl aes-256-cbc -K $encrypted_da2886fcba80_key -iv $encrypted_da2886fcba80_iv -in fabricaaraujo-e9550-0f5107defc2f.json.enc -out fabricaaraujo-e9550-0f5107defc2f.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json